service: lamda-start

provider:
  name: aws
  runtime: nodejs8.10

functions:
  helloWorld:
    handler: controller.run
    events: 
      - http: 
          path: /
          method: get
plugins:
  - serverless-offline